services:
    postgres:
        container_name: postgres_container
        environment:
            - POSTGRES_PASSWORD=Dai0978526675
            # - POSTGRES_USER=postgres  # nếu muốn dùng user mặc định như lệnh docker run
            - PGDATA=/data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - 5432:5432
        networks:
            - postgres
        restart: unless-stopped
        image: postgres

    pgadmin4:
        container_name: pgadmin_container
        environment:
            - PGADMIN_DEFAULT_EMAIL=22028278@vnu.edu.vn
            - PGADMIN_DEFAULT_PASSWORD=Dai0978526675
            - PGADMIN_CONFIG_SERVER_MODE=False
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 5050:80
        networks:
            - postgres
        restart: unless-stopped
        image: dpage/pgadmin4

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:
